# Generated by Django 3.0.5 on 2020-04-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flairPred', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='post',
        ),
    ]
