# Generated by Django 3.0.5 on 2020-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flairPred', '0002_auto_20200425_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
