# Generated by Django 3.0.5 on 2020-04-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flairPred', '0004_auto_20200425_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditpost',
            old_name='inputfile',
            new_name='upload_file',
        ),
    ]
